<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
  <script type="text/javascript" src="my_player.js"></script>
  <meta charset="utf-8">
  <title>Robot interface</title>
</head>
<body onload="init_api()">
  <div class="card" style="width: 640px;">
    <div id="myVideo" class="card-img-top" style="height: 480px; background-color: black;"> </div>
    <button onclick="connect()" value="PLAY" class="btn btn-success">PLAY<button>
  </div>
  <table>
    <tr>
      <td></td>
      <td>
        <button type="submit" method="post" value="Go" name="b1" class="btn btn-primary">Forward</button>
      </td>
      <td></td>
    </tr>
    <tr>
      <td>
        <button type="submit" method="post" value="Left" name="b3" class="btn btn-primary">Left</button>
      </td>
  		<td></td>
      <td>
        <button type="submit" method="post" value="Right" name="b4" class="btn btn-primary">Right</button>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <button type="submit" method="post" value="Down" name="b2" class="btn btn-primary">backward</button>
      </td>
      <td></td>
    </tr>
  </table>

</body>
</html>
